baseURL: "https://andrearichichi.github.io/"
title: Andrea Richichi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Projects
      url: projects/
      weight: 2
    - name: Papers
      url: papers/
      weight: 3
    - name: Courses
      url: courses/
      weight: 4
    - name: Data
      url: data/
      weight: 5
    - name: Blog
      url: blog/
      weight: 6

params:
  description: "Portfolio of Andrea Richichi — MSc student in Artificial Intelligence (University of Trento), Erasmus at NTNU (Aug–Dec 2025). Projects, papers, course notes, datasets, CV, and contact information."
  author: Andrea Richichi
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: auto
  hideFooter: false
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["projects", "papers", "courses", "data", "blog"]
  ShowToc: true
  disableScrollToTop: false
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Andrea Richichi
    subtitle: "MSc student in Artificial Intelligence at the University of Trento; Erasmus exchange at NTNU (Aug–Dec 2025). Interests: language modeling, vision–language, optimization."
    imageUrl: "picture.jpeg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Projects
        url: projects/
      - name: Papers
        url: papers/
      - name: Data
        url: data/
      - name: Courses
        url: courses/
      - name: Tags
        url: tags/
      - name: Archive
        url: archive/
      - name: Blog
        url: blog/

  socialIcons:
    - name: CV
      url: cv.pdf
    - name: Email
      url: mailto:andrea.richichi@unitn.it  # TODO: update if different
    - name: GitHub
      url: https://github.com/andrearichichi
    # - name: LinkedIn           # TODO: uncomment and set your LinkedIn URL
    #   url: https://www.linkedin.com/in/YOUR-HANDLE/

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Andrea Richichi"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
